
services:

  cleanup:
    image: docker-registry.markridgwell.com/credfeto/dev-cleanup:latest
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=$PACKAGES
      - REPOS_LIST=$REPOS_LIST
      - TEMPLATE=$TEMPLATE
      - RELEASE=$RELEASE
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
      - GIT_USER_NAME=$GIT_USER_NAME
      - GIT_USER_EMAIL=$GIT_USER_EMAIL
      - GIT_OPTIMIZE_DAY=3
      - DOTNET_SOURCE=$DOTNET_SOURCE
      - DOTNET_PROXY_HOST=$DOTNET_PROXY_HOST
    volumes:
      - $TRACKING_ROOT/codecleanup/$COMPOSE_PROJECT_NAME:/local/tracking
      - $CACHE_ROOT/codecleanup/$COMPOSE_PROJECT_NAME/nuget:/local/.nuget/packages
      - $CACHE_ROOT/codecleanup/$COMPOSE_PROJECT_NAME/work:/local/work
      - $CONFIG_ROOT/codecleanup/ssh:/local/.ssh:r
      - $CONFIG_ROOT/codecleanup/gnupg.$COMPOSE_PROJECT_NAME:/local/.gnupg
      - $DOTNET_CACHE_ROOT/codecleanup/$COMPOSE_PROJECT_NAME/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/codecleanup/$COMPOSE_PROJECT_NAME/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

  dependencies:
    image: docker-registry.markridgwell.com/credfeto/dev-dependencies:latest
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - REPOS_LIST=$REPOS_LIST
      - TEMPLATE=$TEMPLATE
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
      - GIT_USER_NAME=$GIT_USER_NAME
      - GIT_USER_EMAIL=$GIT_USER_EMAIL
      - GIT_OPTIMIZE_DAY=4
      - DOTNET_SOURCE=$DOTNET_SOURCE
      - DOTNET_PROXY_HOST=$DOTNET_PROXY_HOST
    volumes:
      - $TRACKING_ROOT/dependencies/$COMPOSE_PROJECT_NAME:/local/tracking
      - $CACHE_ROOT/dependencies/$COMPOSE_PROJECT_NAME/nuget:/local/.nuget/packages
      - $CACHE_ROOT/dependencies/$COMPOSE_PROJECT_NAME/work:/local/work
      - $CONFIG_ROOT/dependencies/ssh:/local/.ssh:r
      - $CONFIG_ROOT/dependencies/gnupg.$COMPOSE_PROJECT_NAME:/local/.gnupg
      - $DOTNET_CACHE_ROOT/dependencies/$COMPOSE_PROJECT_NAME/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/dependencies/$COMPOSE_PROJECT_NAME/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

networks:
  updaters:
    driver: bridge
