
services:


  templates:
    image: docker-registry.markridgwell.com/credfeto/dev-templates:latest
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    profiles:
      - templates
      - minimal
      - full
    environment:
      - PACKAGES=$PACKAGES
      - REPOS_LIST=$REPOS_LIST
      - TEMPLATE=$TEMPLATE
      - RELEASE=$RELEASE
      - TEMPLATE_CONFIG=$TEMPLATE_CONFIG
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
      - GIT_USER_NAME=$GIT_USER_NAME
      - GIT_USER_EMAIL=$GIT_USER_EMAIL
      - GIT_OPTIMIZE_DAY=1
      - DOTNET_SOURCE=$DOTNET_SOURCE
      - DOTNET_PROXY_HOST=$DOTNET_PROXY_HOST
    volumes:
      - $TRACKING_ROOT/templateupdate/$COMPOSE_PROJECT_NAME:/local/tracking
      - $CACHE_ROOT/templateupdate/$COMPOSE_PROJECT_NAME/nuget:/local/.nuget/packages
      - $CACHE_ROOT/templateupdate/$COMPOSE_PROJECT_NAME/work:/local/work
      - $CONFIG_ROOT/templateupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/templateupdate/gnupg.$COMPOSE_PROJECT_NAME:/local/.gnupg
      - $DOTNET_CACHE_ROOT/templateupdate/$COMPOSE_PROJECT_NAME/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/templateupdate/$COMPOSE_PROJECT_NAME/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

  packages:
    image: docker-registry.markridgwell.com/credfeto/dev-packages:latest
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    profiles:
      - packages
      - minimal
      - full
    environment:
      - PACKAGES=$PACKAGES
      - REPOS_LIST=$REPOS_LIST
      - TEMPLATE=$TEMPLATE
      - RELEASE=$RELEASE
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
      - GIT_USER_NAME=$GIT_USER_NAME
      - GIT_USER_EMAIL=$GIT_USER_EMAIL
      - GIT_OPTIMIZE_DAY=2
      - DOTNET_SOURCE=$DOTNET_SOURCE
      - DOTNET_PROXY_HOST=$DOTNET_PROXY_HOST
    volumes:
      - $TRACKING_ROOT/packageupdate/$COMPOSE_PROJECT_NAME:/local/tracking
      - $CACHE_ROOT/packageupdate/$COMPOSE_PROJECT_NAME/nuget:/local/.nuget/packages
      - $CACHE_ROOT/packageupdate/$COMPOSE_PROJECT_NAME/work:/local/work
      - $CONFIG_ROOT/packageupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/packageupdate/gnupg.$COMPOSE_PROJECT_NAME:/local/.gnupg
      - $DOTNET_CACHE_ROOT/packageupdate/$COMPOSE_PROJECT_NAME/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/packageupdate/$COMPOSE_PROJECT_NAME/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

networks:
  updaters:
    driver: bridge
